### ISSUE TITLE
Custom WoW/EFNYC URLs are not working on dev/prod deployments

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#1003]
The recent #998 and #1000 aren't working on deployment because environment variables are baked into the static JS bundles when they're first generated, and this happens in a container in CircleCI, _not_ on Heroku.

There are two potential solutions I can think of here:

1. The way we currently deal with this is to simply pass these sorts of configuration parameters in the initial blob that the Django app hands to the rendering (TypeScript) app on each request.  This basically means adding new entries to the [`AppServerInfo`](https://github.com/JustFixNYC/tenants2/blob/1c5e9165f310a82fa1ac8c0c117bf0861cad2646/frontend/lib/app-context.tsx#L26-L84) type in the rendering app and then populating the corresponding entries in the Django app in [`project/views.py`](https://github.com/JustFixNYC/tenants2/blob/1c5e9165f310a82fa1ac8c0c117bf0861cad2646/project/views.py#L248-L260).

    Since you're getting those values from environment variables, you'd then want to move the definition of those environment variables from webpack-land over to `justfix_environment.py`... and then in the rendering components that need to use them, you'd want to grab the `AppContext` to retrieve the `AppServerInfo` for the current request (see [`help-page.tsx`](https://github.com/JustFixNYC/tenants2/blob/1c5e9165f310a82fa1ac8c0c117bf0861cad2646/frontend/lib/pages/help-page.tsx#L8) for an example of this).

2. The other way to do this is to somehow make sure that the relevant environment variables are part of the environment that generates the static assets on CircleCI.  I'm not sure what the best way of doing this is, but it's definitely possible... The one thing I don't like about this approach is that changing the value of an environment variable via Heroku won't actually trigger a rebuild of the static assets, which means that in the future we might be confused when we change an environment variable and nothing happens.  Oy!

**Comment by sraby** [comment]
Ok, will charge ahead with solution 1!

**Comment by sraby** [comment]
Fixed with #1005
