### ISSUE TITLE
Add and/or link to privacy policy

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#101]
The first step of onboarding is supposed to have a link to a privacy policy but it doesn't right now, because I'm not sure where it's supposed to live or what it's supposed to contain.

**Comment by toolness** [comment]
Also, they need to agree to the terms and conditions and/or privacy policy before creating an account. I've added the checkbox for that in #183 but still need to link to the right stuff.

**Comment by romeboards** [comment]
https://www.justfix.nyc/privacy-policy
https://www.justfix.nyc/terms-of-use

I believe these have been updated / are being updated, but here are the links. Georges is going to get plain language bullet points for the modals by 10/18!

**Comment by romeboards** [comment]
**Modal Content**

Your privacy is very important to us! Here are some important things to know:
- Your personal information is secure
- We don’t use your personal information for profit or sell it to third parties
- We use your address to find information about your landlord and your building

Our Privacy Policy enables sharing anonymized data with approved tenant advocacy organizations exclusively to help further our tenants rights mission. The Privacy Policy contains information regarding what data we collect, how we use it, and the choices you have regarding your personal information. If you’d like to read more, please review our full *Privacy Policy and Terms of Use* (links to each are above).

**Comment by toolness** [comment]
Fixed by ce8b4c1.
