### ISSUE TITLE
Consider using a React library to create a shareable accordion menu component 

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#1191]
Some potential resources in mind:

1. [React Accessible Accordion](https://www.npmjs.com/package/react-accessible-accordion)
- seems to be the main package focused on accessibility
- last update was 5 months ago

2. [React Collapsible](https://www.npmjs.com/package/react-collapsible)
- nice animations, but doesn't seem to address accessibility
- last updated 2 months ago

3. [React Native Collapsible](https://www.npmjs.com/package/react-native-collapsible)
- most transparent about maintenance (you can actually see the ppl who maintain it)
- no mention of accessibility
- last updated 15 days ago

4. [Bulma Accordion](https://www.npmjs.com/package/bulma-accordion)
- Bulma extension, uses Bulma styling out of the box
- Doesn't seem well maintained or used (last update 1 year ago)

**Comment by toolness** [comment]
Woot, Sam ended up using the awesome [`<details>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element instead, and is happy with it, so I'm gonna close this.
