### ISSUE TITLE
Migrate our MAILCHIMP_URL to an environment variable

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#1198]
Our newsletter sign-up form in the [footer of NoRent](https://github.com/JustFixNYC/tenants2/blob/5d1e1cc39190f498a6862d8cb5169c267995c1c2/frontend/lib/norent/components/footer.tsx) includes a constant for the subscribe list URL we plug in from Mailchimp. Let's migrate that to an environment variable.

**Comment by toolness** [comment]
Fixed as of #1556!
