### ISSUE TITLE
Add actual tests for the NoRent letter builder front-end

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#1226]
Lots of functionality is being added in e.g. #1222 but we're just running smoke tests for it all right now.  Need to actually hunker down and write some real tests.

**Comment by toolness** [comment]
Might want to also add some tests for #1239, although it's so scroll-focused that I'm not really sure what would help.

**Comment by sraby** [comment]
Also, we should add tests for the function outlined in https://github.com/JustFixNYC/tenants2/pull/1314#discussion_r416188072 !

**Comment by toolness** [comment]
Hey I think this is pretty much done, gonna close it!
