### ISSUE TITLE
Decide whether to reuse our NorentLetterContent component in the landing page letter preview

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#1244]
It would be ideal for us to reuse our <NorentLetterContent> component on the landing page so that we stay DRY and changes to the actual content mirror this. However, it's possible that Tahnee might want the letter preview on the actual landing page to be a more formal tone like this, more as a descriptive element rather than actually showing a true sample of what the letter looks like (as with the actual embedded letter preview iFrame on the "The Letter" page).

Brought up in conversation here: https://github.com/JustFixNYC/tenants2/pull/1242#discussion_r412925516

**Comment by sraby** [comment]
@toolness I forgot to circle back to this but Tahnee and I talked and it seems like we do want to keep the letter content on the landing page different from the actual embedded letter previews. It's more a descriptive element getting across the concept, when the preview really gets into the details.

**Comment by toolness** [comment]
oh right that makes sense--do you think it's maybe worth adding a comment to the code that explains this, so that future us (and/or new contributors) know why it is the way it is?

**Comment by sraby** [comment]
Yes, lets! I'll make a new issue for that
