### ISSUE TITLE
Consider moving NORENT_PRIVACY_POLICY_URL to a common module

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#1280]
See comment in https://github.com/JustFixNYC/tenants2/pull/1278#discussion_r414795858

**Comment by sraby** [comment]
@toolness I believe you fixed this in https://github.com/JustFixNYC/tenants2/pull/1337, no?

**Comment by toolness** [comment]
Oops, you're right! Closing this now.
