### ISSUE TITLE
Landlord name/address are required by server, but at least one shouldn't be

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#136]
In #135 our copy says "If you don't know, we'll look it up for you" but the server-side currently marks both these fields as required, which contradicts this.

I think the address field can be optional, as the landlord's address doesn't appear anywhere on the LoC, but making the name optional poses questions for the preview letter: if they haven't entered it, should we replace the landlord's name with "Sir or Madam" in the preview letter?  Or should the name field actually be required?  @atreni, what do you think?

**Comment by romeboards** [comment]
On the current version the landlords name is optional - if they don’t enter
it, it defaults to “To whom it may concern” or something similar. Both the
name and address are things that could/should be eventually supplied by our
open data feed!

**Comment by toolness** [comment]
Ah cool, thanks!

Totes re: the open data feed stuff, I'm just implementing the "worst case scenario" right now, where all our feeds etc fail miserably.  This is gonna be much more awesome by launch time!

**Comment by romeboards** [comment]
For sure for sure! So exciting
