### ISSUE TITLE
Use assertion helpers from @justfixnyc/util.

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#1634]
I moved the assertion helpers into the package in https://github.com/JustFixNYC/justfix-ts/pull/9 since WoW is starting to use them, so we should start using them from that package and get rid of them in this codebase.

**Comment by toolness** [comment]
@samaratrilling another good first bug!

**Comment by samaratrilling** [comment]
Atul also suggest a minor improvement to one of the monorepo helper functions. Doing this would allow for experience pushing new versions of monorepo library to npm.

**Comment by toolness** [comment]
> Atul also suggest a minor improvement to one of the monorepo helper functions. Doing this would allow for experience pushing new versions of monorepo library to npm.

Yeah! Here's the issue: https://github.com/JustFixNYC/justfix-ts/issues/24

**Comment by toolness** [comment]
This was fixed by #2043, woot!
