### ISSUE TITLE
Add some kind of "forgot your password" solution

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#171]
Until we implement #170 we need to have _some_ kind of solution for users who forgot their password, even if it's "call us at this number".

**Comment by toolness** [comment]
Ok we can just put our phone number in there for now!

**Comment by toolness** [comment]
Or text...

**Comment by romeboards** [comment]
Point folks to support@justfix.nyc

**Comment by toolness** [comment]
Fixed by 9fbd999.
