### ISSUE TITLE
Add slack integration

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#173]
In particular, whenever someone finishes the letter of complaint process and wants us to mail it, we need to be notified so we can act on it.

**Comment by toolness** [comment]
Er, it's possible we might use Airtable or even a CSV data export type thing for this, so hold off on it until we talk to Adalky.

**Comment by romeboards** [comment]
Lets discuss this together on 10/15, and figure out the best MVP! I like the idea of logging things into Django Admin as long as its usable for Adalky

**Comment by toolness** [comment]
I added some very basic integration in #269, we don't actually send any slack notifications currently though. But we have the infrastructure to do so now.

**Comment by toolness** [comment]
Fixed in 0cbe49ddab5a26fb9b4905980f9b4901ae16c16a.
