### ISSUE TITLE
Unable to file HP action w/o making it signing fee waiver or making it an emergency HP action

### ISSUE THREAD

**Issue by greveritt** [JustFixNYC/tenants2#1740]
Hi everyone,

I have been unable to file an HP action against a landlord who has been harassing me because the HP action flow keeps attaching a fee waiver, and it would be a false statement to say that I cannot afford the fee. A housing attorney told me that the court is taking regular, non-emergency HP actions again, but I can only see an option for filing an emergency HP action with a court fee waiver.

I notice that the `stepsToFillOut` for emergency HP actions does not include a step that lets you specify whether or not you need to fill out the waiver: https://github.com/JustFixNYC/tenants2/blob/4e278d1ffd9cbde87002da844102bcd689036da1/frontend/lib/hpaction/emergency-hp-action.tsx#L561

Thanks.

**Comment by toolness** [comment]
Hey @greveritt, my understanding is that you got this cleared up with our support staff and were ultimately able to file a case, so I'm going to close this issue for now, but feel free to re-open it if you disagree.
