### ISSUE TITLE
Sending NoRent reminders now results in "SMS queue is full" errors

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#2057]
The `send_norent_reminders` command, added in #1727, was originally something that could be run across all our California-based users without problems.  We now have enough users, however, that this command eventually has SMS sends fail because of [Twilio Error 21611](https://www.twilio.com/docs/api/errors/21611):

```
Unable to create record: SMS queue is full
```

Right now I am working around this by just waiting a while after getting this message and re-running `send_norent_reminders`, but it should be noted that because this command sends SMS messages from the same number we use for all our other SMS activity, it's quite possible that this is also causing other products to fail.

Given the non-urgent nature of the norent reminders, it might be useful to set up a periodic task (say, once per hour) that e.g. sends out up to 100 norent reminders if needed.

**Comment by toolness** [comment]
Ok, with #2108 we can now have our code that sends SMS reminders keep track of whether a SMS still needs to be sent to a recipient, or if we tried but failed and the SMS no longer needs to be sent (due to e.g. the number being invalid, the user having blocked us, etc).  This way multiple runs of the code won't keep trying to re-send SMS messages that don't need to be re-sent.

Next, we can either add an option to `send_norent_reminders` that allows a maximum number of reminders to be sent, so we can add it as a periodic task, or do something with Celery to schedule the sending of the reminders at appropriate intervals so we don't trigger "SMS queue is full" errors (and so we don't send SMS messages at inopportune times of day).

**Comment by toolness** [comment]
Ok, in #2111 I've added something that will help with this in the short-term at least:

> [This PR] also adds a `--seconds-between-texts` option to the `send_norent_reminders` command, which will help with #2057 by making it possible for us to manually throttle the rate at which we give SMS messages to Twilio, reducing the possibility that we will run into "SMS queue is full" errors.

**Comment by samaratrilling** [comment]
Given that we probably won't be sending too many mass NoRent reminders, I'm going to close this for now. The infrastructure works pretty well with `--seconds-between-texts` - Twilio also has some new options for having multiple phone numbers, which is not too hard to set up if we wanted to set up a NoRent-specific messagingService with multiple phone numbers. https://support.twilio.com/hc/en-us/articles/223181308-Getting-started-with-Messaging-Services#h_01F906R1JEWZA226ZR3CKR0Y4F
