### ISSUE TITLE
Cap Phone # spaces

### ISSUE THREAD

**Issue by atreni** [JustFixNYC/tenants2#209]
![screen shot 2018-09-25 at 5 31 30 pm](https://user-images.githubusercontent.com/7797826/46044796-cd5ae800-c0e9-11e8-88bd-75c2f4b44a2a.png)

**Comment by toolness** [comment]
Aw dang, what browser are you on?  It looks like my checkbox CSS from #201 didn't take... 

Wait, that looks like Chrome. Which is weird because it looks great on _my_ Chrome, but I'm on windows... blargrgrgh css!!!

<img src="https://i.imgur.com/Q3cUg29.gif">
