### ISSUE TITLE
Checkboxes are still small on some browsers

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#211]
Despite my efforts to make checkboxes big in #201, they still appear to be tiny on some browsers, as mentioned in https://github.com/JustFixNYC/tenants2/issues/209#issuecomment-424513835:

> ![screen shot 2018-09-25 at 5 31 30 pm](https://user-images.githubusercontent.com/7797826/46044796-cd5ae800-c0e9-11e8-88bd-75c2f4b44a2a.png)

**Comment by toolness** [comment]
Why would a browser ever make checkboxes that frickin' small. I do not understand.

**Comment by romeboards** [comment]
Oh weird - are these bulma-ified or browser + CSS?

**Comment by toolness** [comment]
So Bulma intentionally has the philosophy of not modifying browser-native form inputs when it comes to radios and checkboxes. From their [docs](https://bulma.io/documentation/form/checkbox/):

> It is intentionally not styled, to preserve cross-browser compatibility and the user experience. 

So that's cool but the only problem is that the default user experience browsers provide for checkboxes and radios isn't very accessible... given e.g. [Fitts's law](https://en.wikipedia.org/wiki/Fitts%27s_law) they're so small by default that they're hard to click on!

I tried fixing things by just telling the inputs to take up more space in #201, which actually works really well on IE11, Edge, and Chrome on Windows.  But Firefox just puts extra space around the checkbox/radio instead of scaling it, and apparently Chrome on OS X does nothing at all, perhaps because Apple doesn't like it when its native widgets get scaled or some dumb thing.

Blehh why do browsers/OSes have to make the default experience so horrible.
