### ISSUE TITLE
Ensure the letter preview has a maximum height on all browsers

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#224]
I believe it has a max height set in the CSS, but some cell phone browsers aren't paying attention to it, which means that some users might miss the final buttons at the very bottom.

**Comment by toolness** [comment]
Argh, this is not as simple as setting `max-height`, apparently it is an iOS-specific problem: https://stackoverflow.com/questions/34320046/iframe-height-issues-on-ios-mobile-safari

**Comment by romeboards** [comment]
Still seeing issues :~(
