### ISSUE TITLE
Update letter of complaint confirmation page content

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#275]
There should be two versions of the final results page - one for folks who are having JustFix mail the letter and one for folks mailing on their own. See the [content doc](https://docs.google.com/document/d/1jTrP0QSAJYHArZ6QCgVqg-f7f6Dnvp0EK945O1amBJk/edit?usp=sharing) for the most recent conception of this - it looks like we still need to lock things down for mail-on-my-own folks.

**Comment by romeboards** [comment]
@toolness let me know if/when you can push a starting point for this and I can take it from there. thank yeeeeu

**Comment by toolness** [comment]
Ok I just did the structural changes for this in #298, @romeboards can you add the proper content?

**Comment by toolness** [comment]
Um, I am trying to reassign this to @romeboards but something weird is happening with GitHub.

**Comment by romeboards** [comment]
Resolved by #318
