### ISSUE TITLE
Address autocomplete field should push elements down, not overlay

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#276]
Definitely more to learn about this but the hypothesis is that this will make the autocomplete fields more noticeable - especially if the border around that area is also darkened to match the other form field elements.

**Comment by romeboards** [comment]
Resolved by #318

**Comment by toolness** [comment]
Note that we've actually reverted this for the time being in #890, but we should definitely keep investigating ways to make the autocomplete results more noticeable!
