### ISSUE TITLE
Ensure that app can successfully track Objectives and Key Results

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#278]
[Objectives and Key Results](https://docs.google.com/spreadsheets/d/1etBQRMyQ4UV8zU9uIJ--X0vw7sMEKOMA6ZCgXrNuIP0/edit?usp=sharing)

Most importantly, we should have a viewpoint on where users might be dropping off and any errors they might be experiencing. Traditionally these pitfalls occur in address validation, and a lack of ability to navigate to pages / engage with core features.

**Comment by toolness** [comment]
Here's the article about doing funnel tracking stuff with GA: https://medium.com/analytics-for-humans/how-to-set-up-a-goal-funnel-visualization-report-on-google-analytics-to-identify-cart-abandonment-9f63d46ec4df

**Comment by romeboards** [comment]
Closing for the time being.
