### ISSUE TITLE
Add a basic airtable integration

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#286]
Let's talk about this! This could be a simple way to add to HRP, and it would add the following fields to a table:

- Tenant Name
- Tenant Address
- Tenant Phone Number
- Tenant can be texted?
- Link to letter (is this possible with the current version?
- Landlord name
- Landlord address
- Date added (to the table)
- Status (all would be "pending" i.e. need to send the letter)
- Tracking number (added later)
- Date sent (added later, maybe automatically when status is updated?)

We can easily create a trigger from Airtable (when status is changed?) to trigger the RapidPro/TextIt campaigns. How does that sound?? Let's discuss!

**Comment by toolness** [comment]
Ok, I added all the syncing infrastructure in #287 but still need to sync the specific fields (right now just primary key and name are synced). Punted that to #288 and closing this issue!
