### ISSUE TITLE
Make LoC Times New Roman

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#301]
Generally let's make it as imposing as possible!

Another stretch goal:

Wording/logo about JustFix

**Comment by toolness** [comment]
So this is what the LoC looks like if I change its CSS to use `font-family: serif`:

> ![loc-serif](https://user-images.githubusercontent.com/124687/47256514-b6d94f80-d44f-11e8-8206-616badcd3b05.png)

I'm not sure what font that is, but it doesn't look much like TNR to me, though at least it's serifed.  If that's not good enough, well, according to Wikipedia, Times New Roman is a proprietary font, so we probably can't use it, but there is a free alternative called [Liberation Serif](https://en.wikipedia.org/wiki/Liberation_fonts) which is metrically equivalent.
