### ISSUE TITLE
Margins are off on printed letters

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#345]
Remember this was a pain from the first version...

![image from ios 3](https://user-images.githubusercontent.com/627751/47509360-f505b300-d843-11e8-81d0-e8db01dc9dc3.jpg)

**Comment by toolness** [comment]
Wait, I am confused--when I look at the PDF in a PDF viewer, the margins look fine... is this actually a problem with the printer or something?

**Comment by toolness** [comment]
Ok, the problem was that the default page size was A4, which is slightly taller than U.S. letter, hence the appearance of a tiny bottom margin.  Just changed the page size in ec0b1b6 so this should no longer be an issue!
