### ISSUE TITLE
Warning modal about not having a lease is shown when "Other" is picked instead of "I don't have a lease"

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#374]
Wait, so when #367 was submitted, I forgot that we still actually showed an option called "I don't have a lease".  Shouldn't we be showing the warning modal that starts with "If you do not have a lease" for _that_ option, rather than for the "other" option?

**Comment by romeboards** [comment]
Curious about this - what is the breakdown of how current users have answered this question? Has anyone selected this option thus far?

**Comment by toolness** [comment]
Oh, good question... because we're now syncing this field to airtable, we can actually ask airtable!  Looks like *no one* has yet selected this as an option...
