### ISSUE TITLE
Onboarding flow makes references to letter even if user is onboarding for HP action

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#388]
When implementing #387, I noticed that there are a few mentions of the letter of complaint in the onboarding flow (primarily in modals), which will be confusing for users who are onboarding for HP Actions.  We should figure out some way around this, either by making the onboarding text more generic, or by specializing the content to take the signup intent into account.

**Comment by toolness** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BUG | This modal looks like it's from the letter process not HPA](https://trello.com/c/8sFB938K/36-bug-this-modal-looks-like-its-from-the-letter-process-not-hpa)

**Comment by jokudasai** [comment]
@toolness Let's make them generic. We had decided on language a few weeks back though I don't see it documented anywhere. Do we revisit?

**Comment by toolness** [comment]
Oh sorry, this was actually fixed in #754 -- closing now!

**Comment by jokudasai** [comment]
Super, thank you @toolness
