### ISSUE TITLE
Should we assume users aren't necessarily in NYC?

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#47]
It occurred to me that we have some engagements coming up that assume non-NYC users.

So it might make sense to plan ahead for this without over-rotating on it, e.g. by making NYC-specific data in our database be not too tightly coupled to more general information, or something.  I'm not really sure what this means but I figured I'd mention it here so we can keep it in mind (I know, not a useful criteria for a GitHub issue but I'm not sure where else to mention it right now).

**Comment by romeboards** [comment]
Yes! Good to call out. I think by incorporating GeoSearch
<https://geosearch.planninglabs.nyc/> as the address autocomplete/typeahead
we can have somewhat restrictive validation rules on only allowing NYC
addresses (and more specifically to the data model, BBLs) to be registered
to the system. This is basically how the current tenant app works.

Happy to discuss further if you think theres a better approach....
ᐧ

**Comment by toolness** [comment]
Ok cool, closing this issue now!
