### ISSUE TITLE
Letters are rendered with today's date, not when they were requested

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#506]
Ack! This just came up when trying to send a copy of the letter to a tenant. When I grabbed the letter from Django, it had today's date (3/8/2019) instead of when the letter was originally created/sent (in this case, 12/11/2018). The date should be frozen in time for the instance of bringing something like this to court or to show when it was originally requested.

LMK if you need more info on this, thank you!

**Comment by toolness** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lock letter down at time of sending (could be changed later)](https://trello.com/c/9FOeC7sR/5-lock-letter-down-at-time-of-sending-could-be-changed-later)
