### ISSUE TITLE
DDO SQL query can sometimes return empty results

### ISSUE THREAD

**Issue by toolness** [JustFixNYC/tenants2#841]
For some addresses, such as 77 Park Avenue in Manhattan, the DDO SQL query can return empty results, which currently raises an exception because we expect there to be a result row.  We should fix this and possibly add a unit test to ensure it doesn't happen again.

**Comment by sraby** [comment]
@toolness Georges also found that 888 Grand Concourse also doesn't return any results (when WOW has no trouble with this address)

https://files.slack.com/files-pri/T0GFSAH35-FSAPA5T5Z/screen_shot_2020-01-14_at_2.19.36_pm.png

**Comment by toolness** [comment]
I believe this was fixed by #2040.  In any case, 77 Park Avenue in Manhattan now displays a "Sorry, we don't recognize the address you entered" message, instead of crashing: https://demo.justfix.nyc/en/?address=77%20PARK%20AVENUE&borough=MANHATTAN

Closing this issue!
