### ISSUE TITLE
Add a test for GenerateUserRhFormInput function in the RH app

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#895]
Due to the cognitive complexity of the GenerateUserRhFormInput function, we should add a test!

**Comment by toolness** [comment]
BTW, if #914 is merged before this is finished, you could actually refactor `GenerateUserRhFormInput()` to use optional chaining, which could make it easier to read!  (I wonder if codeclimate would actually think it has less cognitive complexity, or if it even recognizes optional chaining syntax yet...)

**Comment by toolness** [comment]
Looks like this was fixed by #1011!
